[package]
name = "osmium-router"
version = "0.1.0"
edition = "2024"

[dependencies]
osmium-agent.workspace = true
osmium-common.workspace = true

serde.workspace = true
tokio.workspace = true
tokio-tungstenite = { version = "0.30.0", features = ["rustls", "rustls-native-certs", "rustls-tls-native-roots", "rustls-tls-webpki-roots", "tokio-rustls"] }
uuid.workspace = true
thiserror.workspace = true
pretty_env_logger.workspace = true
log.workspace = true
