/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the role of an account.
         * @description Roles are nested seniority levels, so an account holds exactly one or none. An account cannot change its own role, so an administrator cannot demote themselves.
         */
        put: operations["replaceRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every account. */
        get: operations["list"];
        put?: never;
        /** Create an account with a chosen username and password. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hosts. */
        get: operations["list_1"];
        put?: never;
        /**
         * Enrol a host.
         * @description Returns the enrolment token once. Only its hash is stored, so it cannot be retrieved later - a lost token is replaced by re-enrolling. No address is taken: the host connects to Osmium, so its location is observed on connect.
         */
        post: operations["enrol"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hosts/{id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a new enrolment token.
         * @description Invalidates the previous token and closes the host's current connection, so it must reconnect with the new one. Use this instead of deleting a host when a token leaks - the host keeps its agents.
         */
        post: operations["rotateToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the password of the authenticated account.
         * @description Requires the current password. Any authenticated account may call this for itself.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for an access token. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every agent. */
        get: operations["list_2"];
        put?: never;
        /**
         * Create an agent slot.
         * @description Nothing has touched Minecraft at this point; the agent starts UNLINKED.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the host to set this agent up.
         * @description Sends `setup_agent` and moves the agent to SETUP_PENDING. Osmium does not perform or observe the login - the host reports back a verdict.
         */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect the agent from its Minecraft server. */
        post: operations["disconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect the agent to its Minecraft server. */
        post: operations["connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Speak in game as this agent.
         * @description Impersonation: this says something under an account you own, so it is gated separately from fleet.control.
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an account.
         * @description An account cannot delete itself, so an administrator cannot lock themselves out.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /**
         * Edit another account.
         * @description Supplying a password resets it without knowing the current one. An account cannot target itself here - use PATCH /api/users/me and POST /api/auth/password - so changing your own password always requires the current one.
         */
        patch: operations["update"];
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit the authenticated account.
         * @description Renaming yourself invalidates tokens issued under the old username, since the token subject no longer resolves. Log in again afterwards.
         */
        patch: operations["updateSelf"];
        trace?: never;
    };
    "/api/hosts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a host.
         * @description Cascades to its agents, which cannot run without it. Invalidates the token.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        /**
         * Rename a host.
         * @description Only the name is editable; address, version and reachability are observed from the connection rather than configured.
         */
        patch: operations["rename"];
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one agent. */
        get: operations["get"];
        put?: never;
        post?: never;
        /** Delete an agent. */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        /**
         * Rename an agent or move it to another server.
         * @description Omitted fields are left alone. Moving does not affect credentials - the account is the same wherever it joins - but the agent must be offline first.
         */
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/stream/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream every host and agent change.
         * @description Events: `agent`, `agent-removed`, `host`, `host-removed`. Payloads match the REST responses, so a client replaces the resource in place rather than refetching.
         */
        get: operations["fleet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream one agent's changes. */
        get: operations["agent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every role with its permission nodes. */
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated account. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent operator actions, newest first.
         * @description Entries are kept for 30 days by default and purged daily.
         */
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Replaces the role of an account. Null clears it, leaving no permissions. */
        UpdateRoleRequest: {
            role?: string | null;
        };
        /** @description A user account. Passwords are never returned. */
        UserResponse: {
            /** Format: int64 */
            id?: number;
            username?: string;
            /**
             * @description Assigned role, or null when the account has none.
             * @example administrator
             */
            role?: string | null;
            /** @description Permission nodes granted by the assigned role. */
            nodes?: string[];
        };
        /** @description Creates an account with an administrator-chosen username and password. */
        CreateUserRequest: {
            username: string;
            password?: string;
            /** @description Role name to assign. Must already exist. Omit for no permissions. */
            role?: string | null;
        };
        /** @description Enrols a host. No address: the host dials in, so its location is observed. */
        CreateHostRequest: {
            name: string;
        };
        /** @description A freshly enrolled host, with its enrolment token shown exactly once. */
        HostEnrolledResponse: {
            host?: components["schemas"]["HostResponse"];
            /** @description Give this to the host. It is hashed on the server and never shown again. */
            token?: string;
        };
        /** @description A host. Reachability is derived from the heartbeat, not stored. */
        HostResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @description Observed when the host connects. Null until it first dials in. */
            address?: string | null;
            hostVersion?: string | null;
            /** Format: date-time */
            lastSeenAt?: string | null;
            reachable?: boolean;
            /** Format: int64 */
            agentCount?: number;
        };
        /** @description Rotates the password of the authenticated account. */
        PasswordChangeRequest: {
            currentPassword: string;
            newPassword?: string;
        };
        /** @description Credentials for a login attempt. */
        LoginRequest: {
            /** @example admin */
            username: string;
            /** @example admin */
            password: string;
        };
        /** @description A freshly issued access token. */
        LoginResponse: {
            /** @description Signed JWT to send as `Authorization: Bearer <token>`. */
            token?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        /** @description Creates an agent slot. Nothing has touched Minecraft at this point. */
        CreateAgentRequest: {
            label: string;
            /** Format: int64 */
            hostId?: number;
            /** @example mc.example.com:25565 */
            serverAddress: string;
        };
        /** @description An agent. Only its Minecraft identity is stored, never a credential. */
        AgentResponse: {
            /** Format: int64 */
            id?: number;
            label?: string;
            /** Format: int64 */
            hostId?: number;
            hostName?: string;
            serverAddress?: string;
            /**
             * @description Stored state, adjusted to STALE when the owning host is unreachable.
             * @enum {string}
             */
            state?: "UNLINKED" | "SETUP_PENDING" | "LINKED" | "ONLINE" | "NEEDS_RELINK" | "CONNECT_FAILED" | "STALE";
            mcUsername?: string | null;
            mcUuid?: string | null;
        };
        /** @description Asks the host to set the agent up. The method is a mechanism the operator chose, relayed to the host uninterpreted. It must never identify an account. */
        SetupAgentRequest: {
            /** @example device_code */
            method: string;
        };
        /** @description Sends a chat message as an agent. This is impersonation - gated on fleet.chat. */
        ChatRequest: {
            message: string;
        };
        /** @description Edits any account. Only an administrator can set a password without knowing the old one. */
        UpdateUserRequest: {
            username: string;
            /** @description Omit to leave the password untouched. */
            password?: string | null;
        };
        /** @description Edits the authenticated account. The role is deliberately not editable here. */
        UpdateSelfRequest: {
            username: string;
        };
        /** @description Renames a host. Everything else about a host is observed, not configured. */
        UpdateHostRequest: {
            name: string;
        };
        /** @description Edits an agent. Omitted fields are left alone. Moving an agent to another Minecraft server does not affect its credentials - the account is the account, whichever server it joins - but it must not be connected at the time. */
        UpdateAgentRequest: {
            label?: string | null;
            /** @description Move the agent to this server. Only while it is not online. */
            serverAddress?: string | null;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        /** @description A role and the permission nodes it grants. */
        RoleResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            nodes?: string[];
        };
        /** @description One operator action: who did what, to which agent or host. */
        AuditEntryResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            at?: string;
            account?: string;
            /** @enum {string} */
            action?: "AGENT_CREATE" | "AGENT_UPDATE" | "AGENT_DELETE" | "AGENT_SETUP" | "AGENT_CONNECT" | "AGENT_DISCONNECT" | "AGENT_CHAT" | "HOST_ENROL" | "HOST_RENAME" | "HOST_ROTATE_TOKEN" | "HOST_DELETE" | "USER_CREATE" | "USER_UPDATE" | "USER_DELETE" | "USER_ROLE_CHANGE" | "USER_PASSWORD_CHANGE";
            target?: string;
            detail?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    replaceRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Unknown role name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.role.write`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description No such account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description The account is the caller's own. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Missing node `user.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Account created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Blank username, short password or unknown role. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.create`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Username already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All hosts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"][];
                };
            };
            /** @description Missing node `fleet.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"][];
                };
            };
        };
    };
    enrol: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHostRequest"];
            };
        };
        responses: {
            /** @description Host enrolled; token returned once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description Blank or over-long name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description Missing node `fleet.login`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description Name already enrolled. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
        };
    };
    rotateToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New token, returned once. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description Missing node `fleet.login`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description No such host. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description New password rejected. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or wrong current password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unknown username or wrong password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"][];
                };
            };
            /** @description Missing node `fleet.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description Agent created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Invalid fields, or unknown host. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `fleet.control`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Label already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupAgentRequest"];
            };
        };
        responses: {
            /** @description Command accepted; agent is SETUP_PENDING. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `fleet.login`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Setup already running, or the agent is online. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The owning host is not connected. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    disconnect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `fleet.control`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The agent is not online. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The owning host is not connected. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    connect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `fleet.control`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The agent has not been set up. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The owning host is not connected. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Command accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Blank or over-long message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `fleet.chat`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The agent is not online. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The owning host is not connected. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing node `user.delete`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account is the caller's own. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Blank username or password outside the allowed length. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.edit`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description No such account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Username already taken, or the account is the caller's own. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    updateSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSelfRequest"];
            };
        };
        responses: {
            /** @description Updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Blank or over-long username. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.edit.self`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Username already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host and its agents removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing node `fleet.login`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such host. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHostRequest"];
            };
        };
        responses: {
            /** @description Updated host. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
            /** @description Blank or over-long name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
            /** @description Missing node `fleet.login`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
            /** @description No such host. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
            /** @description Name already enrolled. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `fleet.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing node `fleet.control`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description Updated agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Blank or over-long field. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `fleet.control`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Label taken, or the agent is online. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    fleet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
            /** @description Missing node `fleet.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
            /** @description Missing node `fleet.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All roles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleResponse"][];
                };
            };
            /** @description Missing node `role.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleResponse"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.read.self`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                /** @description How many entries to return, newest first. Clamped to 1..1000. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditEntryResponse"][];
                };
            };
            /** @description Missing node `audit.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditEntryResponse"][];
                };
            };
        };
    };
}
