/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the role of an account.
         * @description Roles are nested seniority levels, so an account holds exactly one or none. An account cannot change its own role, so an administrator cannot demote themselves.
         */
        put: operations["replaceRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schematics/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upload"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Point the agent at a Minecraft server, or at none.
         * @description Null unassigns it, leaving it set up and idle. Offline only: this decides what the next connection targets, and changing it under a live session would describe a session that is not happening. Credentials are untouched either way.
         */
        put: operations["assignServer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every account. */
        get: operations["list"];
        put?: never;
        /** Create an account with a chosen username and password. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/sessions/revoke-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign an account out of every session.
         * @description Revokes every refresh token and every access token already issued to it, leaving the account itself alone. For when somebody's laptop is gone and they are not around to do it themselves.
         */
        post: operations["revokeSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schematics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schematics/{id}/reanalyse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reanalyse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hosts. */
        get: operations["list_2"];
        put?: never;
        /**
         * Enrol a host.
         * @description Returns the enrolment token once. Only its hash is stored, so it cannot be retrieved later - a lost token is replaced by re-enrolling. No address is taken: the host connects to Osmium, so its location is observed on connect.
         */
        post: operations["enrol"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hosts/{id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a new enrolment token.
         * @description Invalidates the previous token and closes the host's current connection, so it must reconnect with the new one. Use this instead of deleting a host when a token leaks - the host keeps its agents.
         */
        post: operations["rotateToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions/revoke-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out of every session, everywhere.
         * @description Revokes every refresh token **and** every access token already issued — the latter is what a password change alone did not do.
         */
        post: operations["revokeAllSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session-alert/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss the replayed-session notice.
         * @description Marks it read. A later replay raises it again.
         */
        post: operations["acknowledgeSessionAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a new access token from the refresh cookie.
         * @description Rotates: the presented token is spent and a successor replaces the cookie. The session expiry does not move, so refreshing cannot extend a session past its login.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the password of the authenticated account.
         * @description Requires the current password. Any authenticated account may call this for itself.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session.
         * @description Revokes the refresh token and every successor of it, then clears the cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a session.
         * @description The access token comes back in the body, for the caller to hold in memory. The refresh token is set as an HttpOnly cookie and never reaches JavaScript.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every agent. */
        get: operations["list_3"];
        put?: never;
        /**
         * Create an agent slot.
         * @description Nothing has touched Minecraft at this point; the agent starts UNLINKED.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the host to set this agent up.
         * @description Sends `setup_agent` and moves the agent to SETUP_PENDING. Osmium does not perform or observe the login - the host reports back a verdict.
         */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect the agent from its Minecraft server. */
        post: operations["disconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect the agent to its Minecraft server. */
        post: operations["connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Speak in game as this agent.
         * @description Impersonation: this says something under an account you own, so it is gated separately from every other verb. Rate limited per agent, because chat spam is the fastest route to a Minecraft ban and the ban lands on the account, not the operator.
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an account.
         * @description An account cannot delete itself, so an administrator cannot lock themselves out.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /**
         * Edit another account.
         * @description Supplying a password resets it without knowing the current one. An account cannot target itself here - use PATCH /api/users/me and POST /api/auth/password - so changing your own password always requires the current one.
         */
        patch: operations["update"];
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit the authenticated account.
         * @description Renaming yourself invalidates tokens issued under the old username, since the token subject no longer resolves. Log in again afterwards.
         */
        patch: operations["updateSelf"];
        trace?: never;
    };
    "/api/schematics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["find"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["rename"];
        trace?: never;
    };
    "/api/hosts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a host.
         * @description Cascades to its agents, which cannot run without it. Invalidates the token.
         */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        /**
         * Rename a host.
         * @description Only the name is editable; address, version and reachability are observed from the connection rather than configured.
         */
        patch: operations["rename_1"];
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one agent. */
        get: operations["get"];
        put?: never;
        post?: never;
        /** Delete an agent. */
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        /**
         * Rename an agent.
         * @description Omitted fields are left alone. Where an agent plays is set through `PUT /api/agents/{id}/server`, which has its own preconditions.
         */
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream everything this account is entitled to see change.
         * @description Events: `agent`, `agent-removed`, `host`, `host-removed`, `chat`, `activity`, `telemetry`, `user`, `user-removed`, `audit`, `permissions`. Resource payloads match the REST responses, so a client replaces what it holds rather than refetching; `chat`, `activity` and `audit` are single lines to append, and `telemetry` is `{ agentId, telemetry }` to merge, published on a fixed tick rather than per reported sample.
         *
         *     **Each event carries its own permission.** Opening the stream needs only `user.read.self`, since every account has to be able to hear about itself; what actually arrives is decided per event, so `agent` reaches only `agent.read` and `audit` only `audit.read`. `permissions` is addressed to a single account when its own role changes and carries what `/api/auth/me` returns. Authority is re-read on a 30s tick, so a demotion narrows an open stream rather than needing a reconnect.
         */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream one agent's changes.
         * @description The same events as the whole stream, filtered to this agent. A server's global chat arrives here too, under whichever agent currently forwards it, so a view showing one agent's conversation filters on `scope`.
         */
        get: operations["agent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schematics/{id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["split"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schematics/{id}/shape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["shape"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schematics/{id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["materials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every role with its permission nodes. */
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One page of chat, newest first.
         * @description Pass exactly one of `agentId` or `server`.
         *
         *                 `agentId` gives the conversation to or about that agent, and excludes the global
         *                 channel: that is identical for every agent on the server and would bury the lines that
         *                 are actually about the one you are looking at.
         *
         *                 `server` gives everything that happened there - the global channel forwarded once by the
         *                 elected listener, plus whispers, proximity chat and the agents' own outbound lines. Not
         *                 the mirror of the above: a whisper to one agent is still something that happened on that
         *                 server.
         *
         *                 Pages by cursor, not by offset: chat arrives while it is being read. Send `nextCursor`
         *                 from the previous response to continue. Kept for 3 days.
         */
        get: operations["list_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/avatars/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A player's head.
         * @description Accepts a Minecraft username or UUID. Fetched from a skin service and cached, so no operator's browser talks to it directly.
         */
        get: operations["head"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The account's own live sessions.
         * @description Only the tip of each rotation chain, with the caller's own marked. The address is only meaningful where the deployment's proxy headers are trusted, and the user agent is self-declared by the browser.
         */
        get: operations["sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated account. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One page of operator actions, newest first.
         * @description Pages by cursor, not by offset: the trail grows while it is being read, so an offset
         *                 would repeat or skip entries between requests. Send `nextCursor` from the previous
         *                 response to continue; a null `nextCursor` means the trail ended.
         *
         *                 Entries are kept for 30 days by default and purged daily.
         */
        get: operations["list_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The trail for a date range, as a CSV attachment.
         * @description `from` is inclusive and `to` exclusive, both ISO-8601 instants, so the caller decides
         *                 what timezone a "day" means rather than having UTC assumed for it.
         *
         *                 The range is capped at the moment the export starts, so a `to` in the future is not an
         *                 error and the file cannot contain the record of its own export.
         *
         *                 Columns are `at,account,action,target,detail`, always in English and never translated:
         *                 an export is read by tooling and kept as a record, so its shape cannot depend on who
         *                 pressed the button. Every field is quoted, and a value a spreadsheet would run as a
         *                 formula keeps its text and gains a leading apostrophe.
         *
         *                 Writes an audit entry of its own before any row is sent.
         */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One page of agent incidents, newest first.
         * @description Every agent's incidents merged, or one agent's when `agentId` is given.
         *
         *                 Pages by cursor, not by offset: incidents arrive while the feed is being read. Send
         *                 `nextCursor` from the previous response to continue. Kept for 10 days.
         */
        get: operations["list_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * End one of your own sessions.
         * @description Ending the current one leaves this browser signed out at the next refresh.
         */
        delete: operations["endSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Replaces the role of an account. Null clears it, leaving no permissions. */
        UpdateRoleRequest: {
            role?: string | null;
        };
        /** @description A user account. Passwords are never returned. */
        UserResponse: {
            /** Format: int64 */
            id?: number;
            username?: string;
            /**
             * @description Assigned role, or null when the account has none.
             * @example administrator
             */
            role?: string | null;
            /** @description Permission nodes granted by the assigned role. */
            nodes?: string[];
            /**
             * Format: date-time
             * @description When a refresh token for this account was replayed, if the operator has not been shown it yet. Null the rest of the time, which is nearly always.
             */
            sessionAlertAt?: string | null;
        };
        SchematicContentResponse: {
            format?: string | null;
            /** Format: int32 */
            dataVersion?: number | null;
            /** Format: int64 */
            volume?: number | null;
            /** Format: int64 */
            blockCount?: number | null;
            /** Format: int32 */
            regionCount?: number | null;
            /** Format: int32 */
            originX?: number | null;
            /** Format: int32 */
            originY?: number | null;
            /** Format: int32 */
            originZ?: number | null;
            /** Format: int32 */
            sizeX?: number | null;
            /** Format: int32 */
            sizeY?: number | null;
            /** Format: int32 */
            sizeZ?: number | null;
            /** Format: int32 */
            cellSize?: number | null;
            outdated?: boolean;
        };
        SchematicResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            originalFilename?: string;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: int64 */
            receivedBytes?: number;
            /** @enum {string} */
            status?: "UPLOADING" | "PENDING" | "ANALYSING" | "READY" | "FAILED";
            /** Format: int32 */
            progressPercent?: number;
            /** Format: int32 */
            queuePosition?: number | null;
            contentHash?: string | null;
            content?: components["schemas"]["SchematicContentResponse"];
            failure?: string | null;
            uploadedBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description Points an agent at a Minecraft server, or at none. Separate from both setup and editing: the account is the same account wherever it joins, so where it plays is its own decision and changing it touches no credential. */
        AssignServerRequest: {
            /**
             * @description Null unassigns it, leaving the agent set up and idle.
             * @example mc.example.com:25565
             */
            serverAddress?: string | null;
        };
        /** @description An agent. Only its Minecraft identity is stored, never a credential. */
        AgentResponse: {
            /** Format: int64 */
            id?: number;
            label?: string;
            /** Format: int64 */
            hostId?: number;
            hostName?: string;
            /** @description Where it plays, or null when it is assigned nowhere and cannot connect. */
            serverAddress?: string | null;
            /**
             * @description Stored state, adjusted to STALE when the owning host is unreachable.
             * @enum {string}
             */
            state?: "UNLINKED" | "SETUP_PENDING" | "LINKED" | "ONLINE" | "NEEDS_RELINK" | "CONNECT_FAILED" | "STALE";
            mcUsername?: string | null;
            mcUuid?: string | null;
            /**
             * Format: date-time
             * @description When the agent last entered the game. Null while it is not online.
             */
            onlineSince?: string | null;
            /** @description Latest vitals, or null when the agent has not reported recently. */
            telemetry?: components["schemas"]["AgentTelemetryResponse"] | null;
            /** @description True when this agent forwards its server's global chat. One per server, elected by the backend - a server with none has no global feed. */
            chatListener?: boolean;
        };
        /** @description An agent's latest reported vitals. Never stored - if an agent has not reported recently this is null, rather than showing something an hour old as though it were now. */
        AgentTelemetryResponse: {
            /**
             * Format: int32
             * @description Out of 20.
             * @example 18
             */
            health?: number;
            /**
             * Format: int32
             * @description Out of 20.
             * @example 17
             */
            food?: number;
            position?: components["schemas"]["PositionResponse"];
            /** @example overworld */
            dimension?: string;
            /**
             * Format: int32
             * @description Round trip to the Minecraft server.
             * @example 42
             */
            pingMs?: number;
            nearby?: components["schemas"]["NearbyPlayerResponse"][];
        };
        /** @description A player standing near an agent in game. */
        NearbyPlayerResponse: {
            name?: string;
            /**
             * Format: double
             * @description Blocks away.
             * @example 12.4
             */
            distance?: number;
            /** @description Where the player is, when the host reported it. */
            position?: components["schemas"]["PositionResponse"] | null;
            isAgent?: boolean;
        };
        /** @description A position in the world. */
        PositionResponse: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
            /** Format: double */
            z?: number;
        };
        /** @description Creates an account with an administrator-chosen username and password. */
        CreateUserRequest: {
            username: string;
            password?: string;
            /** @description Role name to assign. Must already exist. Omit for no permissions. */
            role?: string | null;
        };
        CreateSchematicRequest: {
            name: string;
            filename: string;
            /** Format: int64 */
            sizeBytes?: number;
        };
        /** @description Enrols a host. No address: the host dials in, so its location is observed. */
        CreateHostRequest: {
            name: string;
        };
        /** @description A freshly enrolled host, with its enrolment token shown exactly once. */
        HostEnrolledResponse: {
            host?: components["schemas"]["HostResponse"];
            /** @description Give this to the host. It is hashed on the server and never shown again. */
            token?: string;
        };
        /** @description A host. Reachability is derived from the heartbeat, not stored. */
        HostResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @description Observed when the host connects. Null until it first dials in. */
            hostVersion?: string | null;
            /** Format: date-time */
            lastSeenAt?: string | null;
            reachable?: boolean;
            /** Format: int64 */
            agentCount?: number;
            /** @description What this host can log in with, from its handshake. Empty while it is disconnected, and empty for a host that advertises nothing - which can then set nothing up. */
            loginMethods?: components["schemas"]["LoginMethodResponse"][];
        };
        /** @description A freshly issued access token. */
        LoginResponse: {
            /** @description Signed JWT to send as `Authorization: Bearer <token>`. */
            token?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        /** @description Rotates the password of the authenticated account. */
        PasswordChangeRequest: {
            currentPassword: string;
            newPassword?: string;
        };
        /** @description Credentials for a login attempt. */
        LoginRequest: {
            /** @example admin */
            username: string;
            /** @example admin */
            password: string;
        };
        /** @description Creates an agent slot. Nothing has touched Minecraft at this point. */
        CreateAgentRequest: {
            label: string;
            /** Format: int64 */
            hostId?: number;
            /**
             * @description Where it should play, if that is already known.
             * @example mc.example.com:25565
             */
            serverAddress?: string | null;
        };
        /** @description Asks the host to set the agent up. The method is a mechanism the operator chose, relayed to the host uninterpreted. It must never identify an account. */
        SetupAgentRequest: {
            /** @example method_a */
            method: string;
        };
        /** @description Sends a chat message as an agent. This is impersonation - gated on chat. */
        ChatRequest: {
            message: string;
        };
        /** @description Edits any account. Only an administrator can set a password without knowing the old one. */
        UpdateUserRequest: {
            username: string;
            /** @description Omit to leave the password untouched. */
            password?: string | null;
        };
        /** @description Edits the authenticated account. The role is deliberately not editable here. */
        UpdateSelfRequest: {
            username: string;
        };
        RenameSchematicRequest: {
            name: string;
        };
        /** @description Renames a host. Everything else about a host is observed, not configured. */
        UpdateHostRequest: {
            name: string;
        };
        /** @description Renames an agent. Where it plays is set through `PUT /api/agents/{id}/server`, which is a different kind of change and has its own preconditions. */
        UpdateAgentRequest: {
            label?: string | null;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        SegmentResponse: {
            /** Format: int32 */
            ordinal?: number;
            /** Format: int32 */
            minX?: number;
            /** Format: int32 */
            minY?: number;
            /** Format: int32 */
            minZ?: number;
            /** Format: int32 */
            maxX?: number;
            /** Format: int32 */
            maxY?: number;
            /** Format: int32 */
            maxZ?: number;
            /** Format: int64 */
            blocks?: number;
            /** Format: int32 */
            sharePercent?: number;
        };
        SplitResponse: {
            mode?: string;
            /** Format: int32 */
            requested?: number;
            /** Format: int32 */
            parts?: number;
            /** Format: int64 */
            blocks?: number;
            segments?: components["schemas"]["SegmentResponse"][];
        };
        ShapeResponse: {
            /** Format: int32 */
            voxelSize?: number;
            /** Format: int32 */
            originX?: number;
            /** Format: int32 */
            originY?: number;
            /** Format: int32 */
            originZ?: number;
            /** Format: int32 */
            sizeX?: number;
            /** Format: int32 */
            sizeY?: number;
            /** Format: int32 */
            sizeZ?: number;
            /** Format: int32 */
            count?: number;
            /** Format: int32 */
            hidden?: number;
            palette?: string[];
            voxels?: number[];
        };
        MaterialResponse: {
            name?: string;
            /** Format: int64 */
            blocks?: number;
        };
        /** @description A role and the permission nodes it grants. */
        RoleResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            nodes?: string[];
        };
        /** @description One line of Minecraft chat, as the agent that observed it reported it. */
        ChatMessageResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            at?: string;
            /** Format: int64 */
            agentId?: number | null;
            agentLabel?: string;
            serverAddress?: string;
            /** @enum {string} */
            scope?: "OUTBOUND" | "DIRECT" | "LOCAL" | "GLOBAL";
            from?: string;
            text?: string;
        };
        /** @description One page of chat, newest first. */
        ChatPageResponse: {
            items?: components["schemas"]["ChatMessageResponse"][];
            nextCursor?: string | null;
        };
        /** @description One live session. Only the tip of each rotation chain is listed — a spent token is a step in a chain, not something an operator would recognise. */
        SessionResponse: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: date-time
             * @description When this link in the chain was issued.
             */
            startedAt?: string;
            /**
             * Format: date-time
             * @description When the session ends regardless of use. Refreshing does not move it.
             */
            expiresAt?: string;
            /**
             * @description Where it was last seen from, or null when the request carried nothing usable. Only meaningful where the deployment's proxy headers are trusted.
             * @example 203.0.113.7
             */
            clientIp?: string | null;
            /** @description Self-declared by the browser, and not evidence of anything. */
            userAgent?: string | null;
            /** @description True for the session making this request - the one not to end by accident. */
            current?: boolean;
        };
        /** @description One operator action: who did what, to which agent or host. */
        AuditEntryResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            at?: string;
            account?: string;
            /** @enum {string} */
            action?: "AGENT_CREATE" | "AGENT_UPDATE" | "AGENT_DELETE" | "AGENT_SETUP" | "AGENT_CONNECT" | "AGENT_DISCONNECT" | "AGENT_CHAT" | "HOST_ENROL" | "HOST_RENAME" | "HOST_ROTATE_TOKEN" | "HOST_DELETE" | "USER_CREATE" | "USER_UPDATE" | "USER_DELETE" | "USER_ROLE_CHANGE" | "USER_PASSWORD_CHANGE" | "AUDIT_EXPORT" | "SESSION_REUSE_DETECTED" | "SESSION_REVOKED_ALL" | "SCHEMATIC_UPLOAD" | "SCHEMATIC_RENAME" | "SCHEMATIC_DELETE";
            target?: string;
            detail?: string | null;
        };
        /** @description One page of the trail, newest first. */
        AuditPageResponse: {
            items?: components["schemas"]["AuditEntryResponse"][];
            nextCursor?: string | null;
        };
        /** @description Something that happened to an agent: kicked, died, connected, relink needed. */
        ActivityEntryResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            at?: string;
            /** Format: int64 */
            agentId?: number | null;
            agentLabel?: string;
            /** @enum {string} */
            scope?: "SYSTEM" | "LIFECYCLE";
            /** @enum {string} */
            severity?: "INFO" | "WARNING" | "ERROR";
            text?: string;
        };
        /** @description One page of activity, newest first. */
        ActivityPageResponse: {
            items?: components["schemas"]["ActivityEntryResponse"][];
            nextCursor?: string | null;
        };
        /** @description A login mechanism the host advertised in its handshake. The id is opaque to the backend and is relayed to the host verbatim; the copy describes a mechanism, never an account. */
        LoginMethodResponse: {
            /** @example device_code */
            id?: string;
            label?: string | null;
            description?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    replaceRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Unknown role name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.role.write`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description No such account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description The account is the caller's own. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query: {
                offset: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SchematicResponse"];
                };
            };
        };
    };
    assignServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignServerRequest"];
            };
        };
        responses: {
            /** @description Updated agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Over-long address. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `agent.write`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The agent is online. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Missing node `user.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Account created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Blank username, short password or unknown role. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.create`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Username already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    revokeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing node `user.edit`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SchematicResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSchematicRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SchematicResponse"];
                };
            };
        };
    };
    reanalyse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SchematicResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All hosts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"][];
                };
            };
            /** @description Missing node `host.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"][];
                };
            };
        };
    };
    enrol: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHostRequest"];
            };
        };
        responses: {
            /** @description Host enrolled; token returned once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description Blank or over-long name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description Missing node `host.write`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description Name already enrolled. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
        };
    };
    rotateToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New token, returned once. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description Missing node `host.token`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
            /** @description No such host. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostEnrolledResponse"];
                };
            };
        };
    };
    revokeAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acknowledgeSessionAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notice dismissed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                osmium_refresh?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description A new access token, and a rotated cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            /** @description No cookie, or a token that is unknown, expired, revoked or replayed. A replay revokes every session descended from that login. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description New password rejected. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or wrong current password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                osmium_refresh?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Session ended, cookie cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unknown username or wrong password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"][];
                };
            };
            /** @description Missing node `agent.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description Agent created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Invalid fields, or unknown host. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `agent.write`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Label already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupAgentRequest"];
            };
        };
        responses: {
            /** @description Command accepted; agent is SETUP_PENDING. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `agent.setup`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Setup already running, or the agent is online. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The owning host is not connected. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    disconnect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `agent.run`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The agent is not online. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The owning host is not connected. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    connect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `agent.run`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The agent has not been set up, or is assigned to no server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The owning host is not connected. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Command accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Blank or over-long message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `chat.speak`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The agent is not online. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description This agent has been made to speak too often. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description The owning host is not connected. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing node `user.delete`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account is the caller's own. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Blank username or password outside the allowed length. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.edit`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description No such account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Username already taken, or the account is the caller's own. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    updateSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSelfRequest"];
            };
        };
        responses: {
            /** @description Updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Blank or over-long username. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.edit.self`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Username already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    find: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SchematicResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSchematicRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SchematicResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host and its agents removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing node `host.delete`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such host. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHostRequest"];
            };
        };
        responses: {
            /** @description Updated host. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
            /** @description Blank or over-long name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
            /** @description Missing node `host.write`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
            /** @description No such host. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
            /** @description Name already enrolled. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `agent.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing node `agent.delete`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description Updated agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Blank or over-long field. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Missing node `agent.write`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description No such agent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Label already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
            /** @description Missing node `user.read.self`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
            /** @description Missing node `user.read.self`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    split: {
        parameters: {
            query: {
                mode: "COLUMNS" | "LAYERS" | "GRID";
                parts: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SplitResponse"];
                };
            };
        };
    };
    shape: {
        parameters: {
            query?: {
                detail?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShapeResponse"];
                };
            };
        };
    };
    materials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MaterialResponse"][];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All roles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleResponse"][];
                };
            };
            /** @description Missing node `role.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleResponse"][];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: {
                /** @description Conversation to or about this agent. Excludes the server's global chat. */
                agentId?: number;
                /**
                 * @description Global chat on this server address.
                 * @example mc.example.com:25565
                 */
                server?: string;
                /** @description How many lines to return. Clamped to 1..500. */
                limit?: number;
                /** @description `nextCursor` from the previous page. Omit for the newest lines. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of chat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatPageResponse"];
                };
            };
            /** @description Neither or both filters given, or a malformed `cursor`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatPageResponse"];
                };
            };
            /** @description Missing node `chat.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatPageResponse"];
                };
            };
        };
    };
    head: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The head, as an image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Missing node `agent.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description No head: unknown player, malformed identifier, upstream unavailable, or avatars disabled. The caller renders its own fallback either way. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                osmium_refresh?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Live sessions, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"][];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing node `user.read.self`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: {
                /** @description How many entries to return. Clamped to 1..500. */
                limit?: number;
                /** @description `nextCursor` from the previous page. Omit for the newest entries. */
                cursor?: string;
                /** @description Narrows to entries whose account, target, detail or action matches. */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of entries, oldest continuing at `nextCursor`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditPageResponse"];
                };
            };
            /** @description Malformed `cursor`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditPageResponse"];
                };
            };
            /** @description Missing node `audit.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditPageResponse"];
                };
            };
        };
    };
    export: {
        parameters: {
            query: {
                /**
                 * @description Start of the range, inclusive.
                 * @example 2026-07-12T00:00:00Z
                 */
                from: string;
                /**
                 * @description End of the range, exclusive.
                 * @example 2026-08-12T00:00:00Z
                 */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The CSV. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `from` is not before `to`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing node `audit.export`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_7: {
        parameters: {
            query?: {
                /** @description Narrow to one agent. Omit for the whole fleet. */
                agentId?: number;
                /** @description How many entries to return. Clamped to 1..500. */
                limit?: number;
                /** @description `nextCursor` from the previous page. Omit for the newest entries. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of activity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPageResponse"];
                };
            };
            /** @description Malformed `cursor`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPageResponse"];
                };
            };
            /** @description Missing node `activity.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPageResponse"];
                };
            };
        };
    };
    endSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such session **for this account**. Another operator's session is reported the same way as one that does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
