-- A build: a schematic, somewhere in a world, with the substitutions it is built under.
--
-- Its own table rather than columns on `schematics`, because the same schematic is legitimately
-- built more than once — the same tower on two servers, or twice on one at different coordinates,
-- under different substitutions each time. Hanging placement off the schematic would have made the
-- second of those an upload of the same gigabytes again.
--
-- This is also the row a segment will eventually be dispatched from. Nothing does that yet: the
-- pipeline stops at a division, because carrying a segment to a host needs the host side.
CREATE TABLE builds
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Gone with the schematic. A plan to build a file that no longer exists cannot be carried out,
    -- and keeping it would leave a row pointing at nothing for somebody to discover later.
    schematic_id bigint       NOT NULL REFERENCES schematics (id) ON DELETE CASCADE,

    name         VARCHAR(128) NOT NULL UNIQUE,

    -- Where the schematic's minimum corner lands in the world. Null until placed, and all three
    -- together or none: two of three coordinates does not describe a position, and a column-level
    -- default would silently put an unplaced build at the world origin.
    place_x      INTEGER,
    place_y      INTEGER,
    place_z      INTEGER,

    -- By name rather than by foreign key, the same reasoning as the audit trail: the record should
    -- outlive the account that made it.
    created_by   VARCHAR(64)  NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT builds_placement_is_whole
        CHECK ((place_x IS NULL) = (place_y IS NULL) AND (place_y IS NULL) = (place_z IS NULL))
);

CREATE INDEX idx_builds_schematic ON builds (schematic_id);

-- What to put down instead. One row per block being replaced.
--
-- `to_block` is nullable, and null means **place nothing at all**. That is not a special case
-- bolted on: "I do not have forty stacks of diamond" is the ordinary reason to reach for this, and
-- the honest answer to it is a hole rather than a wrong block quietly standing in.
--
-- Neither name is validated against a registry, for the reason the accepted version range already
-- documents: Osmium stores block names as strings and never resolves them, so a name that does not
-- exist looks exactly like one that does. The material list is where an operator sees what is
-- actually in the file.
CREATE TABLE build_substitutions
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    build_id   bigint       NOT NULL REFERENCES builds (id) ON DELETE CASCADE,
    from_block VARCHAR(128) NOT NULL,
    to_block   VARCHAR(128),

    -- One rule per source block. Two rules for the same block is a plan that does not say what it
    -- means, and the database is the only place that can refuse it outright.
    CONSTRAINT build_substitutions_one_per_block UNIQUE (build_id, from_block)
);

CREATE INDEX idx_build_substitutions_build ON build_substitutions (build_id);

-- Hibernate emits the audit action enum as a CHECK constraint rather than a Postgres enum type, so
-- three new constants are a schema change. There is no ALTER for a check constraint, so it is
-- dropped and rewritten in full. See V3.
ALTER TABLE audit_entries DROP CONSTRAINT IF EXISTS audit_entries_action_check;

ALTER TABLE audit_entries
    ADD CONSTRAINT audit_entries_action_check CHECK (action IN (
        'AGENT_CREATE', 'AGENT_UPDATE', 'AGENT_DELETE', 'AGENT_SETUP', 'AGENT_CONNECT',
        'AGENT_DISCONNECT', 'AGENT_CHAT',
        'HOST_ENROL', 'HOST_RENAME', 'HOST_ROTATE_TOKEN', 'HOST_DELETE',
        'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_ROLE_CHANGE', 'USER_PASSWORD_CHANGE',
        'AUDIT_EXPORT',
        'SESSION_REUSE_DETECTED', 'SESSION_REVOKED_ALL',
        'SCHEMATIC_UPLOAD', 'SCHEMATIC_RENAME', 'SCHEMATIC_DELETE',
        'BUILD_CREATE', 'BUILD_UPDATE', 'BUILD_DELETE'
    ));
