-- One execution of one build, on one server, against a frozen division of it.
--
-- A build is a *plan* and stays editable while agents are carrying it out. A run is what was
-- actually started, and must not change under them. So the anchor, the substitutions and the
-- schematic are pinned here rather than read back through `build_id`, and the segments below are
-- rows rather than the recomputed split they came from.
--
-- The split itself is still a pure function — see `splitSchematic`. What is stored is one *result*
-- of it, because progress has to hang off something with an identity, and a recomputed segment has
-- none.
CREATE TABLE build_runs
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    build_id        bigint       NOT NULL REFERENCES builds (id) ON DELETE CASCADE,

    -- Pinned rather than reached through the build, so that deleting or re-reading a schematic can
    -- be refused while this run is live. A frozen split describes cells that no longer exist the
    -- moment the file behind it is re-analysed.
    schematic_id    bigint       NOT NULL REFERENCES schematics (id) ON DELETE CASCADE,

    -- Pinned, not joined through the agents. Agents get reassigned mid-run and can be pointed at a
    -- different server between one segment and the next; the target must not move under the run.
    server_address  VARCHAR(128) NOT NULL,

    state           VARCHAR(16)  NOT NULL,

    -- What was asked for. The segments are the truth; these two are what an operator chose, kept so
    -- the run can say how it was divided without inferring it from the shapes that came out.
    split_mode      VARCHAR(16)  NOT NULL,
    requested_parts INTEGER      NOT NULL,

    -- The anchor as it stood when Start was pressed. NOT NULL where the build's is nullable: a
    -- build with nowhere to stand can exist, a run of one cannot.
    place_x         INTEGER      NOT NULL,
    place_y         INTEGER      NOT NULL,
    place_z         INTEGER      NOT NULL,

    -- The sum of the segments, written once. Not `schematics.block_count`: the split counts only
    -- occupied cells, and a segment that came back empty is not work anybody was given.
    total_blocks    bigint       NOT NULL,

    created_by      VARCHAR(64)  NOT NULL,
    started_at      timestamp with time zone NOT NULL,
    finished_at     timestamp with time zone,

    CONSTRAINT build_runs_state_check CHECK (state IN ('ACTIVE', 'DONE', 'CANCELLED')),

    -- A finished run without a time, or a live one with one, is a row that contradicts itself. The
    -- two fields are one fact written twice, so the database holds them together.
    CONSTRAINT build_runs_finished_when_over CHECK ((state = 'ACTIVE') = (finished_at IS NULL))
);

-- One live run per build per server.
--
-- Two would claim the same blocks in the same place for two sets of agents, and neither would be
-- wrong from where it stood. A partial index rather than application logic because this is a race
-- between two requests, and only the database sees both.
CREATE UNIQUE INDEX uq_build_runs_active
    ON build_runs (build_id, server_address) WHERE state = 'ACTIVE';

CREATE INDEX idx_build_runs_build ON build_runs (build_id);
CREATE INDEX idx_build_runs_schematic ON build_runs (schematic_id);

-- The substitutions as they stood when Start was pressed.
--
-- A copy, not a view. An operator editing the plan mid-run is editing the *next* run: the agents
-- already placing blocks under the old rules must not have half a building under one rule set and
-- half under another.
CREATE TABLE build_run_substitutions
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id     bigint       NOT NULL REFERENCES build_runs (id) ON DELETE CASCADE,
    from_block VARCHAR(128) NOT NULL,
    to_block   VARCHAR(128),

    CONSTRAINT build_run_substitutions_one_per_block UNIQUE (run_id, from_block)
);

CREATE INDEX idx_build_run_substitutions_run ON build_run_substitutions (run_id);

-- One agent's share of a run, in world coordinates.
--
-- World coordinates rather than schematic space because the host does no transform: it is told a
-- box and places what the backend serves for it. Half-open, matching the split it came from —
-- `max` is the first block that is *not* in the segment.
CREATE TABLE build_segments
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         bigint      NOT NULL REFERENCES build_runs (id) ON DELETE CASCADE,

    -- 1-based, in the split's own order: bottom first, then depth, then across — the order the
    -- build happens in, and the number the operator reads.
    ordinal        INTEGER     NOT NULL,

    min_x          INTEGER     NOT NULL,
    min_y          INTEGER     NOT NULL,
    min_z          INTEGER     NOT NULL,
    max_x          INTEGER     NOT NULL,
    max_y          INTEGER     NOT NULL,
    max_z          INTEGER     NOT NULL,

    blocks         bigint      NOT NULL,

    state          VARCHAR(16) NOT NULL,

    -- Nulled rather than blocking the delete: a segment outlives the agent that built it, and an
    -- agent that can never be removed because it once placed blocks is a worse outcome than a
    -- finished segment with no assignee.
    agent_id       bigint      REFERENCES agents (id) ON DELETE SET NULL,

    -- Which is why the label is snapshotted. Same reasoning as `builds.created_by`: the record
    -- should be readable after its subject is gone.
    agent_label    VARCHAR(64),

    -- Last reported, never accumulated. A host that restarts mid-segment recounts what it can see,
    -- and summing deltas would double it.
    --
    -- Deliberately NOT reset when a segment is released: the blocks are still standing in the
    -- world, and the count stays the last thing anybody actually observed until the next agent
    -- surveys and reports its own.
    blocks_placed  bigint      NOT NULL DEFAULT 0,
    last_report_at timestamp with time zone,
    failure_reason VARCHAR(256),

    CONSTRAINT build_segments_ordinal UNIQUE (run_id, ordinal),

    CONSTRAINT build_segments_state_check
        CHECK (state IN ('PENDING', 'ASSIGNED', 'BUILDING', 'DONE', 'FAILED')),

    -- Pending means nobody has it. The reverse is not enforced: a failed or finished segment keeps
    -- its assignee so the trail says who was on it, and an agent deleted underneath one leaves the
    -- column null in every state.
    CONSTRAINT build_segments_pending_is_unassigned
        CHECK (state <> 'PENDING' OR agent_id IS NULL),

    -- Half-open, so a box with no volume is a box nobody can build.
    CONSTRAINT build_segments_box_check
        CHECK (max_x > min_x AND max_y > min_y AND max_z > min_z),

    CONSTRAINT build_segments_blocks_check CHECK (blocks > 0 AND blocks_placed >= 0)
);

CREATE INDEX idx_build_segments_run ON build_segments (run_id);

-- Every read of this is "what is this agent building", on a release or a reassignment. Partial
-- because most segments over a fleet's lifetime have no assignee.
CREATE INDEX idx_build_segments_agent ON build_segments (agent_id) WHERE agent_id IS NOT NULL;

-- Hibernate emits the audit action enum as a CHECK constraint rather than a Postgres enum type, so
-- two new constants are a schema change. There is no ALTER for a check constraint, so it is dropped
-- and rewritten in full. See V3.
ALTER TABLE audit_entries DROP CONSTRAINT IF EXISTS audit_entries_action_check;

ALTER TABLE audit_entries
    ADD CONSTRAINT audit_entries_action_check CHECK (action IN (
        'AGENT_CREATE', 'AGENT_UPDATE', 'AGENT_DELETE', 'AGENT_SETUP', 'AGENT_SETUP_CANCEL',
        'AGENT_CONNECT', 'AGENT_DISCONNECT', 'AGENT_CHAT',
        'HOST_ENROL', 'HOST_RENAME', 'HOST_ROTATE_TOKEN', 'HOST_DELETE',
        'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_ROLE_CHANGE', 'USER_PASSWORD_CHANGE',
        'AUDIT_EXPORT',
        'SESSION_REUSE_DETECTED', 'SESSION_REVOKED_ALL',
        'SCHEMATIC_UPLOAD', 'SCHEMATIC_RENAME', 'SCHEMATIC_DELETE',
        'BUILD_CREATE', 'BUILD_UPDATE', 'BUILD_DELETE',
        'BUILD_RUN_START', 'BUILD_RUN_CANCEL'
    ));
