-- A job: one execution of one build, on one server, against a frozen division of it.
--
-- This is where the pipeline used to stop. A plan says what to build and where; a split says how to
-- divide it between agents; neither had anywhere to be recorded as *happening*. A job is that
-- record, and it is a row rather than a recomputation because progress has to attach to something
-- with an identity.
--
-- **Job, not run.** `agent.run` is already the permission for operating the fleet, and "running the
-- fleet" is what an operator does all day. A third meaning for the same word, sitting next to both,
-- was one reading too many. Job is the word for a unit of dispatched work and collides with nothing.
CREATE TABLE build_jobs
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    build_id        bigint       NOT NULL REFERENCES builds (id) ON DELETE CASCADE,

    -- Pinned rather than reached through the build, so that deleting or re-reading a schematic can
    -- be refused while this job is live. A frozen split describes cells that no longer exist the
    -- moment the file behind it is analysed again.
    schematic_id    bigint       NOT NULL REFERENCES schematics (id) ON DELETE CASCADE,

    -- Pinned, not joined through the agents. Agents get reassigned mid-job and can be pointed at a
    -- different server between one segment and the next; the target must not move under the job.
    server_address  VARCHAR(128) NOT NULL,

    -- ACTIVE is building, PAUSED is stopped and resumable, DONE is finished.
    --
    -- There was a CANCELLED here first, and it was a dead end: it stopped a job and then left
    -- nothing to do with it but delete it, so an operator performed two acts to express one
    -- decision, and work that had been divided and crewed could not be picked up again. Pause keeps
    -- the segments, the assignees and the counts, and resuming is one call.
    --
    -- There is deliberately no FAILED. A job with failed segments is still ACTIVE and needs an
    -- operator, because deciding it is over means picking how many failures are too many, and there
    -- is no honest number.
    state           VARCHAR(16)  NOT NULL,

    -- What was asked for. The segments are the truth; these two are what an operator chose, kept so
    -- the job can say how it was divided without inferring it from the shapes that came out.
    split_mode      VARCHAR(16)  NOT NULL,
    requested_parts INTEGER      NOT NULL,

    -- The anchor as it stood when Start was pressed. NOT NULL where the build's is nullable: a
    -- build with nowhere to stand can exist, a job of one cannot.
    place_x         INTEGER      NOT NULL,
    place_y         INTEGER      NOT NULL,
    place_z         INTEGER      NOT NULL,

    -- The sum of the segments, written once. Not `schematics.block_count`: the split counts only
    -- occupied cells, and a segment that came back empty is not work anybody was given.
    total_blocks    bigint       NOT NULL,

    created_by      VARCHAR(64)  NOT NULL,
    started_at      timestamp with time zone NOT NULL,
    finished_at     timestamp with time zone,

    CONSTRAINT build_jobs_state_check CHECK (state IN ('ACTIVE', 'PAUSED', 'DONE')),

    -- Only a finished job has a finishing time. A paused one has stopped, not finished, so a time
    -- on it would be a date attached to something that did not happen.
    CONSTRAINT build_jobs_finished_when_done CHECK ((state = 'DONE') = (finished_at IS NOT NULL))
);

-- One live job per build per server.
--
-- Two would claim the same blocks in the same place for two sets of agents, and neither would be
-- wrong from where it stood. A partial index rather than application logic because this is a race
-- between two requests, and only the database sees both.
CREATE UNIQUE INDEX uq_build_jobs_active
    ON build_jobs (build_id, server_address) WHERE state = 'ACTIVE';

CREATE INDEX idx_build_jobs_build ON build_jobs (build_id);
CREATE INDEX idx_build_jobs_schematic ON build_jobs (schematic_id);

-- The substitutions as they stood when Start was pressed.
--
-- A copy, not a view. An operator editing the plan mid-job is editing the *next* job: the agents
-- already placing blocks under the old rules must not have half a building under one rule set and
-- half under another.
CREATE TABLE build_job_substitutions
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id     bigint       NOT NULL REFERENCES build_jobs (id) ON DELETE CASCADE,
    from_block VARCHAR(128) NOT NULL,
    to_block   VARCHAR(128),

    CONSTRAINT build_job_substitutions_one_per_block UNIQUE (job_id, from_block)
);

CREATE INDEX idx_build_job_substitutions_job ON build_job_substitutions (job_id);

-- One agent's share of a job, in world coordinates.
--
-- World coordinates rather than schematic space because the host does no transform: it is told a
-- box and places what the backend serves for it. Half-open, matching the split it came from —
-- `max` is the first block that is *not* in the segment.
CREATE TABLE build_segments
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id         bigint      NOT NULL REFERENCES build_jobs (id) ON DELETE CASCADE,

    -- 1-based, in the split's own order: bottom first, then depth, then across — the order the
    -- build happens in, and the number the operator reads.
    ordinal        INTEGER     NOT NULL,

    min_x          INTEGER     NOT NULL,
    min_y          INTEGER     NOT NULL,
    min_z          INTEGER     NOT NULL,
    max_x          INTEGER     NOT NULL,
    max_y          INTEGER     NOT NULL,
    max_z          INTEGER     NOT NULL,

    blocks         bigint      NOT NULL,

    state          VARCHAR(16) NOT NULL,

    -- Nulled rather than blocking the delete: a segment outlives the agent that built it, and an
    -- agent that can never be removed because it once placed blocks is a worse outcome than a
    -- finished segment with no assignee.
    agent_id       bigint      REFERENCES agents (id) ON DELETE SET NULL,

    -- Which is why the label is snapshotted. Same reasoning as `builds.created_by`: the record
    -- should be readable after its subject is gone.
    agent_label    VARCHAR(64),

    -- Last reported, never accumulated. A host that restarts mid-segment recounts what it can see,
    -- and summing deltas would double it.
    --
    -- Deliberately NOT reset when a segment is released: the blocks are still standing in the
    -- world, and the count stays the last thing anybody actually observed until the next agent
    -- surveys and reports its own.
    blocks_placed  bigint      NOT NULL DEFAULT 0,
    last_report_at timestamp with time zone,
    failure_reason VARCHAR(256),

    CONSTRAINT build_segments_ordinal UNIQUE (job_id, ordinal),

    CONSTRAINT build_segments_state_check
        CHECK (state IN ('PENDING', 'ASSIGNED', 'BUILDING', 'DONE', 'FAILED')),

    -- Pending means nobody has it. The reverse is not enforced: a failed or finished segment keeps
    -- its assignee so the trail says who was on it, and an agent deleted underneath one leaves the
    -- column null in every state.
    CONSTRAINT build_segments_pending_is_unassigned
        CHECK (state <> 'PENDING' OR agent_id IS NULL),

    -- Half-open, so a box with no volume is a box nobody can build.
    CONSTRAINT build_segments_box_check
        CHECK (max_x > min_x AND max_y > min_y AND max_z > min_z),

    CONSTRAINT build_segments_blocks_check CHECK (blocks > 0 AND blocks_placed >= 0)
);

CREATE INDEX idx_build_segments_job ON build_segments (job_id);

-- Every read of this is "what is this agent building", on a release or a reassignment. Partial
-- because most segments over a fleet's lifetime have no assignee.
CREATE INDEX idx_build_segments_agent ON build_segments (agent_id) WHERE agent_id IS NOT NULL;

-- One live segment per agent, across every job.
--
-- Refused by the service too, in three places, with a message naming the job in the way. This is
-- the backstop: two requests assigning the same agent at the same moment each see a free agent, and
-- only the database sees both. An agent building two segments at once is not a display problem — it
-- is one bot walking between two sites placing half of each, and the version that looks reasonable
-- in an interface is two segments of the *same* build.
CREATE UNIQUE INDEX uq_build_segments_one_per_agent
    ON build_segments (agent_id) WHERE state IN ('ASSIGNED', 'BUILDING');

-- Hibernate emits the audit action enum as a CHECK constraint rather than a Postgres enum type, so
-- four new constants are a schema change. There is no ALTER for a check constraint, so it is dropped
-- and rewritten in full. See V3.
--
-- Starting, stopping and clearing away are recorded; the assignments underneath them are not. A job
-- is started once and paused a handful of times, while segments move between agents whenever one
-- drops out or cannot finish, and a trail carrying every reassignment is one in which the decision
-- to build at all is buried. Where a piece went is fleet activity, which the agent's own feed
-- already records.
ALTER TABLE audit_entries DROP CONSTRAINT IF EXISTS audit_entries_action_check;

ALTER TABLE audit_entries
    ADD CONSTRAINT audit_entries_action_check CHECK (action IN (
        'AGENT_CREATE', 'AGENT_UPDATE', 'AGENT_DELETE', 'AGENT_SETUP', 'AGENT_SETUP_CANCEL',
        'AGENT_CONNECT', 'AGENT_DISCONNECT', 'AGENT_CHAT',
        'HOST_ENROL', 'HOST_RENAME', 'HOST_ROTATE_TOKEN', 'HOST_DELETE',
        'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_ROLE_CHANGE', 'USER_PASSWORD_CHANGE',
        'AUDIT_EXPORT',
        'SESSION_REUSE_DETECTED', 'SESSION_REVOKED_ALL',
        'SCHEMATIC_UPLOAD', 'SCHEMATIC_RENAME', 'SCHEMATIC_DELETE',
        'BUILD_CREATE', 'BUILD_UPDATE', 'BUILD_DELETE',
        'BUILD_JOB_START', 'BUILD_JOB_PAUSE', 'BUILD_JOB_RESUME', 'BUILD_JOB_DELETE'
    ));
