-- Which agents are on a job, separately from which pieces they are holding.
--
-- A job used to know its crew only through `build_segments.agent_id`, which made the crew a
-- *consequence* of the division: as many agents as there were pieces, each holding one for the life
-- of the job, and an agent between pieces linked to nothing at all.
--
-- That is the model a vertical split cannot live in. A piece that cannot start until the piece below
-- it is finished means agents that are on a job while holding nothing, and under the old shape those
-- agents were invisible - not idle, not waiting, simply not on the job as far as anything could
-- tell. It is also why a reconnecting agent could only be found by the segment it still held.
--
-- So membership is its own row. An agent is on a job because it is in the pool; what it is building
-- right now is a separate question with its own answer, and the scheduler is what puts the two
-- together.
CREATE TABLE build_job_agents
(
    id          bigint                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      bigint                   NOT NULL REFERENCES build_jobs (id) ON DELETE CASCADE,

    -- Cascades rather than nulling, unlike `build_segments.agent_id`. A deleted agent is not on the
    -- job any more, full stop; a segment it finished is still the record of who built it, which is
    -- why that column keeps the row and nulls the reference instead.
    agent_id    bigint                   NOT NULL REFERENCES agents (id) ON DELETE CASCADE,

    -- Snapshotted for the same reason as everywhere else, even though the row dies with the agent:
    -- an audit line about the pool should be readable without joining to something that is gone.
    agent_label VARCHAR(64)              NOT NULL,

    joined_at   timestamp with time zone NOT NULL,

    CONSTRAINT build_job_agents_once UNIQUE (job_id, agent_id)
);

CREATE INDEX idx_build_job_agents_job ON build_job_agents (job_id);

-- One job per agent, across every job.
--
-- The pool is *live* membership, which is what lets this be a plain unique index rather than a
-- partial one over a state that lives on the other table: a finished job's pool is emptied, so a row
-- here always means an agent that is on something right now. Who built which piece survives in
-- `build_segments.agent_label` and does not need this table to say it.
--
-- A paused job keeps its rows, deliberately. Those agents are on that job - that is what paused
-- means - and freeing one is an act with a name.
--
-- The service refuses a second claim first, with a message naming the job in the way. This is the
-- backstop for the race the service cannot see: two starts claiming the same agent at the same
-- moment, where each sees a free agent and only the database sees both.
CREATE UNIQUE INDEX uq_build_job_agents_one_job_per_agent ON build_job_agents (agent_id);
