-- Baseline: the schema as it stood when Flyway took over from ddl-auto=update.
--
-- Written out rather than generated, so the names are readable ones instead of the random
-- ukgwri2vcdni369sh6vjcrn4xti Hibernate produces. Nothing here is new; every table already existed.
--
-- Databases that predate Flyway are adopted with baseline-on-migrate, so this never runs against
-- them - they already have these tables. V2 is what brings them into line.

-- ---- accounts and authorization ------------------------------------------------------------

CREATE TABLE users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(64)  NOT NULL,
    password_hash varchar(255) NOT NULL,
    role_id       bigint,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE roles (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) NOT NULL,
    CONSTRAINT uk_roles_name UNIQUE (name)
);

-- The node id is the node itself: 'fleet.chat' is both the primary key and the string every
-- @PreAuthorize checks, so there is no surrogate id to keep in sync with the annotations.
CREATE TABLE permission_nodes (
    id varchar(64) PRIMARY KEY
);

-- Role inheritance is materialised by DataInitializer rather than walked at check time, so this
-- holds the flattened set for each role and authorization stays one flat lookup.
CREATE TABLE role_nodes (
    role_id bigint      NOT NULL,
    node_id varchar(64) NOT NULL,
    PRIMARY KEY (role_id, node_id),
    CONSTRAINT fk_role_nodes_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_role_nodes_node FOREIGN KEY (node_id) REFERENCES permission_nodes (id)
);

ALTER TABLE users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id);

-- ---- the fleet -----------------------------------------------------------------------------

CREATE TABLE hosts (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(64)  NOT NULL,
    -- Hashed like a password, and shown to the operator exactly once.
    token_hash   varchar(255) NOT NULL,
    -- Observed when the host dials in, never configured: the backend never reaches out to a host.
    address      varchar(128),
    host_version varchar(32),
    last_seen_at timestamp(6) with time zone,
    CONSTRAINT uk_hosts_name UNIQUE (name)
);

CREATE TABLE agents (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label          varchar(64)  NOT NULL,
    host_id        bigint       NOT NULL,
    server_address varchar(128) NOT NULL,
    state          varchar(32)  NOT NULL,
    -- Identity only. A credential must never reach this table.
    mc_username    varchar(32),
    mc_uuid        varchar(64),
    -- Ranks candidates for the chat listener role; reset on every entry into ONLINE.
    online_since   timestamp(6) with time zone,
    -- A default is required, not cosmetic: a not null column with none cannot be added to a table
    -- that already has rows. See the backend README.
    chat_listener  boolean      NOT NULL DEFAULT false,
    CONSTRAINT uk_agents_label UNIQUE (label),
    CONSTRAINT fk_agents_host FOREIGN KEY (host_id) REFERENCES hosts (id),
    CONSTRAINT agents_state_check CHECK (state IN (
        'UNLINKED', 'SETUP_PENDING', 'LINKED', 'ONLINE', 'NEEDS_RELINK', 'CONNECT_FAILED', 'STALE'
    ))
);

-- ---- the three feeds -----------------------------------------------------------------------

-- What operators did. The target is a name rather than a foreign key on purpose: an entry has to
-- outlive its subject, and a cascade would delete the evidence along with it.
CREATE TABLE audit_entries (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at      timestamp(6) with time zone NOT NULL,
    account varchar(64)  NOT NULL,
    action  varchar(32)  NOT NULL,
    target  varchar(128) NOT NULL,
    detail  varchar(512),
    CONSTRAINT audit_entries_action_check CHECK (action IN (
        'AGENT_CREATE', 'AGENT_UPDATE', 'AGENT_DELETE', 'AGENT_SETUP', 'AGENT_CONNECT',
        'AGENT_DISCONNECT', 'AGENT_CHAT',
        'HOST_ENROL', 'HOST_RENAME', 'HOST_ROTATE_TOKEN', 'HOST_DELETE',
        'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_ROLE_CHANGE', 'USER_PASSWORD_CHANGE'
    ))
);

-- What happened to agents. Same no-foreign-key reasoning: "Mason_04 was banned" is exactly the line
-- you want after Mason_04 has been deleted.
CREATE TABLE activity_entries (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at          timestamp(6) with time zone NOT NULL,
    agent_id    bigint,
    agent_label varchar(64)  NOT NULL,
    scope       varchar(16)  NOT NULL,
    severity    varchar(16)  NOT NULL,
    body        varchar(512) NOT NULL,
    CONSTRAINT activity_entries_scope_check CHECK (scope IN ('SYSTEM', 'LIFECYCLE')),
    CONSTRAINT activity_entries_severity_check CHECK (severity IN ('INFO', 'WARNING', 'ERROR'))
);

-- What was said in game. `body` rather than `text`, which is a type name in Postgres and reserved
-- elsewhere. The server is denormalised so a server's feed survives the agent that forwarded it.
CREATE TABLE chat_messages (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at             timestamp(6) with time zone NOT NULL,
    agent_id       bigint,
    agent_label    varchar(64)  NOT NULL,
    server_address varchar(255) NOT NULL,
    scope          varchar(16)  NOT NULL,
    sender         varchar(64)  NOT NULL,
    body           varchar(512) NOT NULL,
    CONSTRAINT chat_messages_scope_check CHECK (scope IN ('OUTBOUND', 'DIRECT', 'LOCAL', 'GLOBAL'))
);

-- Every feed is read newest-first from a keyset cursor on (at, id), so the sort columns follow the
-- filter in each index. Without them, paging deep into a busy feed sorts the whole table.
CREATE INDEX idx_audit_entries_at_id ON audit_entries (at, id);
CREATE INDEX idx_activity_entries_at_id ON activity_entries (at, id);
CREATE INDEX idx_activity_entries_agent ON activity_entries (agent_id, at, id);
CREATE INDEX idx_chat_messages_agent ON chat_messages (agent_id, at, id);
CREATE INDEX idx_chat_messages_server ON chat_messages (server_address, at, id);
