-- A box of world somebody means to dig out or chart, saved the way a build plan is saved.
--
-- **The region half of `builds`.** A build plan is a schematic, a placement and the rules it goes up
-- under; this is the same idea with the file taken out, because there is no file — two corners read
-- off the world are the whole description. It exists for the reasons a build plan exists, none of
-- which are about schematics: the same quarry is dug twice, the same valley is charted again next
-- month, and a box nobody has started is still worth drawing on the map so two people do not plan
-- the same hole.
--
-- Its own table rather than nullable columns on `builds`. A build without a schematic is not a
-- thing — the column is NOT NULL and should stay that way — and half the fields either side mean
-- nothing to the other: a region has no substitutions and no rotation, a build has no second
-- corner.
CREATE TABLE region_plans
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- EXCAVATE or MAP. Never BUILD: a build comes from a file, and its plan is a row in `builds`.
    type           VARCHAR(16)  NOT NULL,

    name           VARCHAR(128) NOT NULL UNIQUE,

    -- Where these coordinates were read, and **required**, unlike a build plan's.
    --
    -- A build plan can be written before anybody knows where it is going, because a schematic is a
    -- shape that exists on its own. Six coordinates are not: they are only a place once they say
    -- which world they were read in, and the same six numbers are a different spot on every server.
    -- A region without them is not an unplaced plan, it is an unanswerable one.
    --
    -- Nor is the server inferred from whoever is sent. Deriving it — the rule a build job follows —
    -- means the box an operator typed against one world's landscape can be dug in another simply by
    -- ticking a different agent, and nothing would say so.
    server_address VARCHAR(255) NOT NULL,
    dimension      VARCHAR(128) NOT NULL,

    -- Half-open, like every box here: max_x is the first block that is *not* in the region. What an
    -- operator types is two inclusive corners either way round; the service sorts them.
    --
    -- A survey is a slab one block thick at the height its agents fly, so min_y is that height and
    -- max_y is one above it. That keeps one shape for every box rather than a special case every
    -- reader would have to know about.
    min_x          INTEGER      NOT NULL,
    min_y          INTEGER      NOT NULL,
    min_z          INTEGER      NOT NULL,
    max_x          INTEGER      NOT NULL,
    max_y          INTEGER      NOT NULL,
    max_z          INTEGER      NOT NULL,

    created_by     VARCHAR(64)  NOT NULL,
    created_at     timestamp with time zone NOT NULL,
    updated_at     timestamp with time zone NOT NULL,

    CONSTRAINT region_plans_type_check CHECK (type IN ('EXCAVATE', 'MAP')),

    -- A region with nothing in it is not a region. Half-open, so equal corners are empty.
    CONSTRAINT region_plans_positive CHECK (max_x > min_x AND max_y > min_y AND max_z > min_z)
);

-- Which plan a region job was started from.
--
-- Nullable, and the check below pairs it with the type: a build job has a `build_id`, a region job
-- has this, and neither has both. Cascading on delete matches `build_id` — and, as there, the
-- service refuses to remove a plan while a job of it is running, so the cascade is the backstop
-- rather than the route anybody takes.
ALTER TABLE build_jobs ADD COLUMN region_plan_id bigint REFERENCES region_plans (id) ON DELETE CASCADE;

CREATE INDEX idx_build_jobs_region_plan ON build_jobs (region_plan_id);

-- Replaces the check from V33, which predates region plans and knew only that a region job had no
-- build. It now says which of the two kinds of plan each kind of job hangs off.
ALTER TABLE build_jobs DROP CONSTRAINT build_jobs_region_by_type;

ALTER TABLE build_jobs ADD CONSTRAINT build_jobs_plan_by_type CHECK (
    (type = 'BUILD'
        AND build_id IS NOT NULL AND schematic_id IS NOT NULL
        AND region_plan_id IS NULL AND region_max_x IS NULL)
        OR (type <> 'BUILD'
        AND build_id IS NULL AND schematic_id IS NULL
        AND region_max_x IS NOT NULL)
);

-- One live job per region per server, the same rule `uq_build_jobs_unfinished` applies to builds:
-- two would claim the same blocks in the same place for two sets of agents, and neither would be
-- wrong from where it stood.
CREATE UNIQUE INDEX uq_region_jobs_unfinished
    ON build_jobs (region_plan_id, server_address) WHERE state IN ('ACTIVE', 'PAUSED');
