-- The schematics an operation builds from.
--
-- The file itself is not here. It lives on a volume, because a schematic Osmium accepts can run to
-- gigabytes and a `bytea` caps out at one — this row is the small permanent description of a large
-- impermanent file, which is what lets the library be listed and sorted without touching a disk.
--
-- `received_bytes` is the whole of resumable upload: a client that lost its connection asks how much
-- arrived and continues from there instead of sending it all again. It is authoritative only
-- alongside the file, and the two can disagree after a crash — see the reconciliation on boot.
CREATE TABLE schematics
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(128) NOT NULL,
    original_filename    VARCHAR(255) NOT NULL,

    size_bytes           BIGINT       NOT NULL,
    received_bytes       BIGINT       NOT NULL DEFAULT 0,

    status               VARCHAR(16)  NOT NULL,
    -- SHA-256, taken during the first analysis pass, which already reads every byte. Null until then.
    -- VARCHAR rather than CHAR: Postgres reports CHAR as `bpchar`, which is a different type to the
    -- one Hibernate expects for a String and fails schema validation on every boot.
    content_hash         VARCHAR(64),

    format               VARCHAR(16),
    data_version         INTEGER,
    volume               BIGINT,
    block_count          BIGINT,
    region_count         INTEGER,
    size_x               INTEGER,
    size_y               INTEGER,
    size_z               INTEGER,

    analysed_bytes       BIGINT       NOT NULL DEFAULT 0,
    analysis_total_bytes BIGINT       NOT NULL DEFAULT 0,

    failure              VARCHAR(512),

    -- A name rather than a foreign key, like the audit trail: the record should outlive the account.
    uploaded_by          VARCHAR(64)  NOT NULL,

    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL,

    CONSTRAINT schematics_status_check
        CHECK (status IN ('UPLOADING', 'PENDING', 'ANALYSING', 'READY', 'FAILED')),
    CONSTRAINT schematics_size_check CHECK (size_bytes > 0),
    CONSTRAINT schematics_received_check CHECK (received_bytes >= 0 AND received_bytes <= size_bytes)
);

-- The library is listed newest first, and that is the only order it is ever read in.
CREATE INDEX idx_schematics_created_at ON schematics (created_at DESC);

-- Found by hash to skip re-reading a file that has already been read. Not unique: two rows may
-- legitimately hold the same build under different names, and an upload in flight has no hash yet.
CREATE INDEX idx_schematics_content_hash ON schematics (content_hash);

-- Hibernate emits the audit action enum as a CHECK constraint rather than a Postgres enum type, so
-- three new constants are a schema change. There is no ALTER for a check constraint, so it is
-- dropped and rewritten in full. See V3.
ALTER TABLE audit_entries DROP CONSTRAINT IF EXISTS audit_entries_action_check;

ALTER TABLE audit_entries
    ADD CONSTRAINT audit_entries_action_check CHECK (action IN (
        'AGENT_CREATE', 'AGENT_UPDATE', 'AGENT_DELETE', 'AGENT_SETUP', 'AGENT_CONNECT',
        'AGENT_DISCONNECT', 'AGENT_CHAT',
        'HOST_ENROL', 'HOST_RENAME', 'HOST_ROTATE_TOKEN', 'HOST_DELETE',
        'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_ROLE_CHANGE', 'USER_PASSWORD_CHANGE',
        'AUDIT_EXPORT',
        'SESSION_REUSE_DETECTED', 'SESSION_REVOKED_ALL',
        'SCHEMATIC_UPLOAD', 'SCHEMATIC_RENAME', 'SCHEMATIC_DELETE'
    ));
