/**
 * Where an item's icon sits on the sprite sheet.
 *
 * Generated by `scripts/viewer-assets.mjs` from the same block atlas the 3D view is rendered from,
 * so a stack of grass blocks in an inventory is the colour of grass on the map and the colour of
 * grass in the viewer. It is about 600 kB, and only a screen showing an inventory needs it.
 *
 * **The newest staged sheet, whatever version an agent is on**, on the same reasoning the map
 * palette uses: an item name means the same item in every release it exists in, and the newest
 * sheet is a superset of the older ones. An item it has no icon for is drawn as an empty square
 * with its name on it, which is what a client would show for an unknown item anyway.
 */

/** Where `viewer-assets.mjs` stages what it generates. */
const ASSETS = '/viewer'

/** The newest of `OSMIUM_VIEWER_VERSIONS`. See `mapPalette.ts`, which pins the same release. */
const VERSION = '26.1'

/** What the sheet's index file holds. */
interface Sheet {
  /** Tiles per row, which is also the number of rows: the sheet is square. */
  across: number
  /** Pixels per tile, at the size the sheet was generated. */
  tile: number
  /** Every item that got an icon, against its position in the grid, reading left to right. */
  items: Record<string, number>
}

/** Everything a stylesheet needs to show one tile of the sheet in a square of any size. */
export interface Icon {
  url: string
  /** `background-size`, as a percentage of the square: the sheet scaled so one tile fills it. */
  size: string
  /** `background-position`, as the percentage pair a sprite sheet is addressed by. */
  position: string
}

let loading: Promise<Sheet> | null = null

/**
 * The sheet's index, fetched once per page.
 *
 * Memoised on the promise rather than on the result, so two cards drawing at once wait on the one
 * request instead of starting two.
 */
export function loadIcons(): Promise<Sheet> {
  loading ??= fetch(`${ASSETS}/itemIcons/${VERSION}.json`)
    .then((response) => {
      // A 200 is not enough: both deployments answer an unknown path with the single-page app's own
      // HTML, so a sheet that was never staged arrives as a successful response full of
      // `<!doctype html>`. See `mapPalette.ts`, which learned this the hard way.
      const kind = response.headers.get('content-type') ?? ''
      if (!response.ok || !kind.includes('json')) {
        throw new Error(
          `the item icons for ${VERSION} are not being served. Run \`npm run predev\` and ` +
            'restart the dev server.',
        )
      }
      return response.json() as Promise<Sheet>
    })
    .catch((failure: unknown) => {
      // Cleared, so a card opened again after a failed fetch tries once more rather than being
      // stuck with a rejected promise for the life of the page.
      loading = null
      throw failure
    })

  return loading
}

/**
 * How to draw one item, or null for one the sheet has no icon for.
 *
 * Percentages rather than pixels, so the same values work at whatever size the square is drawn -
 * a hotbar square and a tooltip's thumbnail address the same sheet without either knowing how big
 * the sheet is. The standard sprite arithmetic: the background is scaled by the number of tiles,
 * and the position runs from 0% to 100% across the tiles that exist rather than across the image.
 */
export function iconFor(sheet: Sheet | null, name: string): Icon | null {
  const at = sheet?.items[name]
  if (sheet === null || at === undefined) return null

  const across = sheet.across
  const x = at % across
  const y = Math.floor(at / across)

  return {
    url: `${ASSETS}/itemIcons/${VERSION}.png`,
    size: `${across * 100}% ${across * 100}%`,
    position: `${(x / (across - 1)) * 100}% ${(y / (across - 1)) * 100}%`,
  }
}
