import type { Palette } from './mapTiles'

/**
 * What colour each block reads as, seen from above.
 *
 * Fetched rather than bundled. The table is generated by `scripts/viewer-assets.mjs` from the same
 * block atlas the 3D view is rendered from - every block's top texture, averaged, with the biome
 * tints the mesher applies - so the map and the viewer cannot disagree about the colour of grass.
 * It is 30 kB, and only the map screen needs it.
 *
 * **The newest staged table, whatever version an agent is on.** A tile carries block names and no
 * version, deliberately: a name means the same block in every release it exists in, and the newest
 * table is a superset of the older ones for everything a map is made of. A block it has no colour
 * for is not drawn, which is the same rule that keeps air out of the picture.
 */

/** Where `viewer-assets.mjs` stages what it generates. */
const ASSETS = '/viewer'

/**
 * The version whose table to load.
 *
 * The newest of `OSMIUM_VIEWER_VERSIONS`, which is the one generated last and covers the most
 * blocks. Named here rather than derived because the staging list is a build-time thing and this is
 * a runtime fetch; the build fails loudly if the pair go out of step, since the file will not exist.
 */
const VERSION = '26.1'

type Rgb = readonly [number, number, number]

let loading: Promise<Palette> | null = null

/** `rrggbb`, as the table stores it. */
function parse(hex: string): Rgb | undefined {
  if (hex.length !== 6) return undefined
  const value = Number.parseInt(hex, 16)
  return Number.isNaN(value) ? undefined : [(value >> 16) & 0xff, (value >> 8) & 0xff, value & 0xff]
}

/**
 * The palette, fetched once per page.
 *
 * Memoised on the promise rather than on the result, so a map that draws while the table is still
 * arriving waits for the one request instead of starting another.
 */
export function loadPalette(): Promise<Palette> {
  loading ??= fetch(`${ASSETS}/mapColours/${VERSION}.json`)
    .then((response) => {
      // A 200 is not enough. Both deployments answer an unknown path with the single-page app's
      // own HTML, so a table that was never staged arrives as a successful response full of
      // `<!doctype html>` - which reaches the screen as a JSON parse error naming a stray `<`, and
      // says nothing about the actual problem. The dev server is the likeliest way to get here: it
      // is told not to watch `public/viewer`, so anything generated under it after the server
      // started stays invisible until it is restarted.
      const kind = response.headers.get('content-type') ?? ''
      if (!response.ok || !kind.includes('json')) {
        throw new Error(
          `the map colours for ${VERSION} are not being served. Run \`npm run predev\` and ` +
            'restart the dev server.',
        )
      }
      return response.json() as Promise<Record<string, string>>
    })
    .then((table) => {
      // Parsed once, on the way in. Doing it per pixel would be a hex parse per block per frame.
      const colours = new Map<string, Rgb>()
      for (const [block, hex] of Object.entries(table)) {
        const rgb = parse(hex)
        if (rgb) colours.set(block, rgb)
      }
      return (block: string) => colours.get(block)
    })
    .catch((failure: unknown) => {
      // Cleared, so a map opened again after a failed fetch tries once more rather than being stuck
      // with a rejected promise for the life of the page.
      loading = null
      throw failure
    })

  return loading
}
